from tkinter import *
import random
def f(n,l,u):
    l = int(l)
    u = int(u)
    n = int(n)
    # i=0
    # while i<=n:
    #     i=i+1
    #     t.insert(END, random.randrange(l,u,1))
    #     t.insert(END, '\n')
    for no in range(n):
        t.insert(END, random.randint(l,u+1))
        t.insert(END,'\n')
    # for x in range(10):
    # print random.randint(1,101)

def callback():
    # print (e1.get())
    # print (e2.get())
    # print (e3.get())
    t.insert(END,'\n')
    t.insert(END, 'n='+e1.get()+'\n')
    t.insert(END, 'lower='+e2.get()+'\n')
    t.insert(END, 'upper='+e3.get()+'\n')
    t.insert(END,'\n')
    # t.insert(END, f(e1.get(),e2.get(),e3.get()))
    f(e1.get(),e2.get(),e3.get())
r=Tk()
r.title('Test Cases')
button = Button(r, text='Generate',width = 25,command=callback)
# Label(r, text='Number of numbers').grid(row=0)
# Label(r, text='Lower limit').grid(row=1)
# Label(r, text='Upper limit').grid(row=2)
Label(r, text='Number of numbers').pack()
Label(r, text='Lower limit').pack()
Label(r, text='Upper limit').pack()
e1 = Entry(r)
e2 = Entry(r)
e3 = Entry(r)
e1.pack()
e2.pack()
e3.pack()
# e1.grid(row=0, column=1)
# e2.grid(row=1, column=1)
# e3.grid(row=2, column=1)
#button.grid(row=3, column=1)
button.pack()
msg = 'Testing'
# messageVar = Message(r,text=msg)
# messageVar.config(bg='lightgreen')
# messageVar.grid(row=4,column=1)
#scrollbar.grid(row=4,column=40)
scrollbar = Scrollbar(r)
scrollbar.pack(side = RIGHT)
t = Text(r,height=200,width=30, yscrollcommand = scrollbar.set)
# t.grid(row=4,column=1)
t.pack(side=LEFT,fill=BOTH)
# for i in range(10):
#     # t.insert(END, t1+'\n')
#     # t.insert(END, t2+'\n')
#     # t.insert(END, t3+'\n')
#     t.insert(END,msg+'\n')
scrollbar.config(command = t.yview)
mainloop()
e1 = Entry(r,width=50)
e2 = Entry(r,width=50)
e3 = Entry(r,width=50)
e1.pack()
e2.pack()
e3.pack()
t1 = e1.get()
t2 = e2.get()
t3 = e3.get()
n = int(t1)
m = StringVar()
m = t1
# t.insert(END, t1+'\n')
# t.insert(END, t2+'\n')
# t.insert(END, t2+'\n')